config/routes.rb
Rails.application.routes.draw do
  get 'relationships/create'
  get 'relationships/destroy'
  namespace :admin do
    resources :users
  end
  resources :users, only: [:index, :new, :create, :edit, :update, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  # resources :labels
  # resources :betweens, only: [:create, :destroy, :show]
  root to:'tasks#index'
  resources :tasks do
    collection do
      post :confirm
    end
  end

end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  validates :daytime, presence: true
  belongs_to :user
  # default_scope -> { order(created_at: :desc) }
  enum status: { 未着手: 1, 着手: 2, 完了: 3 }
  enum priority: { 低: 1, 中: 2, 高: 3 }
  scope :search_title, -> (search_title) { where("title LIKE ?", "%#{search_title}%") }
  scope :search_status, -> (search_status) { where(status: search_status)}
  scope :search_priority, -> (search_priority) { where(priority: search_priority)}
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  # before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def index
    # @tasks = Task.all.order(params[:sort_expired])
    if params[:sort_expired]
      @tasks = Kaminari.paginate_array(Task.all.order(endtime_at: :desc)).page(params[:page]).per(3)  

    elsif params[:sort_priority] 
      @tasks = Kaminari.paginate_array(current_user.tasks.order(priority: :desc)).page(params[:page]).per(3)

    elsif params[:search]
      if params[:search_title].present? && params[:search_status].present?
        @tasks = Kaminari.paginate_array(current_user.tasks.search_title(params[:search_title]).search_status(params[:search_status])).page(params[:page]).per(3)

      elsif params[:search_title].present?
        @tasks = Kaminari.paginate_array(current_user.tasks.search_title(params[:search_title])).page(params[:page]).per(3)

      elsif params[:search_status].present?
        @tasks = Kaminari.paginate_array(current_user.tasks.search_status(params[:search_status])).page(params[:page]).per(3)

      elsif params[:search_priority].present?
        @tasks = Kaminari.paginate_array(current_user.tasks.search_priority(params[:search_priority])).page(params[:page]).per(3)

      else
        @tasks = Kaminari.paginate_array(current_user.tasks.order(id: :desc)).page(params[:page]).per(3)
      end
      
    else
      @tasks = Kaminari.paginate_array(current_user.tasks.order(id: :desc)).page(params[:page]).per(3)
      # binding.pry
    end
  end

  def new
    @task = Task.new
  end
  def self.search(search)
    return Task.all unless search
    Task.where(['title LIKE ?', "%#{search}%"])
  end

  def create
    @task = current_user.tasks.build(task_params)
    # @task = Task.new(task_params)
    # if params[:back]
    #    render :new
    if @task.save
      # @task = current_user.tasks.build(picture_params)
      redirect_to tasks_path, notice: 'タスクを投稿しました'
    else
      render :new
    end
  end

  # def confirm
  #   @task = current_user.tasks.build(task_params)
  #   render :new if @task.invalid?  
  # end
  def update
    if @task.update_attributes(task_params)
      flash[:success] = "タスクを更新しました"
      redirect_to tasks_path
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice: 'タスクを削除しました'
  end

  def show
    
  end

  def edit
  end

  private
  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title,:content,:daytime,:endtime_at,:status,:priority)
    
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
    def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_tasks_path
    elsif action_name == 'edit'
      task_path
    end
  end
end

app/views/tasks/_form.html.erb
<%= form_with(model:@task, local:true) do |form| %>
  <% if @task.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@task.errors.count, "error") %> prohibited this <%= @task.daytime %> from being saved:</h2>
    <ul>
    <% @task.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
  <%= form.label :daytime %>
  <br>
  <%= form.date_field :daytime %>
  <br>
  <%= form.label :title %>
  <br>
  <%= form.text_field :title %>
  <br>
  <%= form.label :content %>
  <br>
  <%= form.text_field :content %>
  <br>
  <%= form.label :期限 %>
  <br>
  <%= form.datetime_field :endtime_at, value: Time.zone.now %>
  <%#= form.datetime_select :endtime_at %>
  <br>
  <%= form.select :status,  Task.statuses.keys %>
  <br>
  <%= form.select :priority,  Task.priorities.keys %>
  <br>
  
  <br>
  <% if action_name == 'new' %>
  <%= form.submit '投稿する' %>
  <% else %>
  <%= form.submit '更新する' %>
  <% end %>
<% end %>

app/views/tasks/edit.html.erb
<h1>編集画面</h1>
<%= render 'form' %>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>
<div class = "navgation">
<%= link_to '期限並び替え', tasks_path(sort_expired: "true") %>
<%= link_to '優先順位で並び替え', tasks_path(sort_priority: "true") %>
</div>
<button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
検索ボックス <span class="caret"></span><ul class="dropdown-menu">
<div class="search_box" >
<%= form_with(local: true, method: :get, url: tasks_path ) do |form| %>
  <p class="input"><%= form.label :search_title, "タスク名" %>
  <%= form.text_field :search_title, placeholder: "タスク名で検索" %></p>
  <p class="input"><%= form.label :search_status, "ステータス" %>
  <%= form.select :search_status, Task.statuses.keys, { include_blank: '選択してください'} %></p>
  <p class="input"><%= form.label :search_priority, "優先順位" %>
  <%= form.select :search_priority, Task.priorities.keys, { include_blank: '選択してください'} %></p>
  <p class="input"><%= form.submit "検索", name: "search" %></p>
  <% end %>
  </div>
  </ul>
  </button>
 
  

<table border = '1' class = "task_table">
  <thead>
    <th>日時</th>
    <th>タイトル</th>
    <th>内容</th>
    <th>期限</th>
    <th>ステータス</th>
    <th>優先順位</th>
    <th>詳細</th>
    <th>編集</th>
    <th>削除</th>
  </thead>
  <tbody>
  
    <% @tasks.each do |form| %>
        <tr class="task_row">
          <td><%= form.daytime %></td>
          <td><%= form.title %></td>
          <td><%= form.content %></td>
          <td><%= form.endtime_at %></td>
          <td><%= form.status %></td>
          <td><%= form.priority %></td>
          <td><%= link_to '詳細', task_path(form.id) %></td>
          <td><%= link_to '編集', edit_task_path(form.id) %></td>
          <td><%= link_to '削除', task_path(form.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
  </tbody>
</table>
<div class = "new_task_btn">
<button type="button" class="btn btn-default navbar-btn"><%= link_to 'タスクを追加する', new_task_path %></button>

<% if current_user.admin? %>
<button type="button" class="btn btn-default navbar-btn"><%= link_to '管理者画面へ', admin_users_path %></button>
<% end %>

</div>
<div class="pagination_block">
    <%= paginate @tasks %>
</div>

app/views/tasks/new.html.erb
<h1>新タスク投稿</h1>
<%= render 'form' %>
<%= link_to '戻る', tasks_path %>

app/views/tasks/show.html.erb
<h1>登録内容</h1>
  <p>日時:<%= @task.daytime %></p>
  <p>タイトル:<%= @task.title %></p>
  <p>内容:<%= @task.content %></p>
  <p>期限:<%= @task.endtime_at %></p>
  <p>期限:<%= @task.status %></p>
  <p>優先順位:<%= @task.priority %></p>
<%= link_to '編集', edit_task_path(@task) %>
<%= link_to '戻る', tasks_path %>